api-version: 1.13
name: LockBlock
main: me.LockBlock.Main
version : 1.0
commands:
   Lock:
      description: blank
      usage: /<command> 
   speed:
      description: Set Fly Speed
      usage: /<command>     